### ISSUE TITLE
ACCESS explicit names 

### ISSUE THREAD

**Issue by bltzr** [Vidvox/OSCQueryProposal#18]
As I proposed as a part of the (now-closed)  #11:
The proposed syntax could IMHO be more readable if using explicit names instead of numbers  for the ACCESS query 
I have no strong opinion about what would be the best set, but here are some proposals to depart from: {none,get,set,getset} or {none, read-only,write-only, read/write,}

**Comment by bltzr** [comment]
hey there !
since there is some progress in implementing OSCquery, I guess now's the time to give another litlle bump to this: as long as more or less everything else in OSCquery is human-readable, why do we keep using these unexpressive values for defining access modes ?
any strong reason, or is it just because nobody really cared about this?

**Comment by jcelerier** [comment]
+1

**Comment by bltzr** [comment]
the explanation proposed in the specs (a binary mask) perfectly makes sense, so I'm closing this
