### ISSUE TITLE
Levels of the proposal

### ISSUE THREAD

**Issue by lov** [Vidvox/OSCQueryProposal#25]
Minimum and optional attributes has been already mentioned in the proposal, however, it could be a bit misleading because of the formatting, maybe its just me :) Anyway, setting a "level" for the attribute must be implemented could be useful.

So, the absolute **minimum** set of attributes could be (as the proposal states it now):
- FULL_PATH
- CONTENTS

I can't agree more with this, since this is really needed to achieve the main goal of the proposal - querying an OSC applications address space.

However, since the TYPE and RANGE attributes are optional, there should be a suggested value on application level - I think the 0-1 range with floats are the most common. While I know setting this value should not be part of this tutorial, a recommendation is always helpful.

**Optional** attributes
- DESCRIPTION
- TYPE
- VALUE
- RANGE
- ACCESS
- TAGS
- CLIPMODE
- UNIT

**Streaming**

In my opinion streaming should be an extension in the proposal, because its not exactly related to the main goal of the proposal, but defines OSC over TCP. Of course, since the proposal is TCP based as well that is a good idea to make a lazy definition here so servers and clients could be compatible with this extension.

*\* Path changes**

Although this is indeed very important, I believe this should be optional too, since it not 100% related to the main goal of the proposal, which is discovering OSC address space - at least in my opinion.

**Comment by mrRay** [comment]
howdy-

>it could be a bit misleading because of the formatting

d'oh- i've moved some stuff around, please let me know if it's still not sufficiently clear...

>In my opinion streaming should be an extension in the proposal, because its not exactly related to the main goal of the proposal, but defines OSC over TCP

my feelings about this functionality have been ambivalent since it was brought up.  i'd love to hear more opinions about this- i get the impression that some of the people who are interested in this proposal view it as necessary/very important...

>** Path changes** Although this is indeed very important, I believe this should be optional too, since it not 100% related to the main goal of the proposal, which is discovering OSC address space

i'm inclined to agree with you, but i couldn't think of a more elegant way to notify clients of changes in the server's address space.  i'd love to hear your thoughts on alternatives to accomplishing this!

**Comment by lov** [comment]
> i've moved some stuff around, please let me know if it's still not sufficiently clear...

thanks Ray, its awesome now! :)

> i'm inclined to agree with you, but i couldn't think of a more elegant way to notify clients of changes in the server's address space. i'd love to hear your thoughts on alternatives to accomplishing this!

Although I could not mention any better alternatives to accomplishing this, but I can imagine that having an application with a static number OSC address space, where there is no need to push out anything to the client, since the OSC addresses won't be changed over the time.

**Comment by jcelerier** [comment]
About this, maybe the advertisment of supported levels could look like an optional array attribute, with all the extensions supported by the server ? e.g.


    "EXTENSIONS" : { 
        "STREAMING" : {
            "OSCCLIENT_IP": ... // as in #31 
        }
        "PATH_CHANGES": true
    }

etc...

**Comment by lov** [comment]
> About this, maybe the advertisment of supported levels could look like an optional array attribute...

Yes, that is a cool idea.

@jcelerier Please don't get me wrong, I'm super-happy to see all of your ideas about how to extend the protocols functionality, but as I see now there are still a couple of very important open questions regarding to even the "minimal" attributes set like #24 #26 etc. which are related to how to protocol works in general.

I think we should keep focusing on those first, and present the cornerstones of the protocol on the "minimal" level before trying to extend it in a variety of ways. If we miss that, this protocol might be just another un-succesfull try to make a finally well-supported and popular OSC query protocol. 
https://github.com/mrRay/OSCQueryProposal#goal

**Comment by jcelerier** [comment]
@lov, you mentioned in a mail removing DESCRIPTION from the set of mandatory attribute. I'm ok with this, so just writing it here for the records. 

About CONTENTS, I feel that it should not be mandatory to put if the node is a leaf. However of course it has to be supported by a conforming spec.

**Comment by lov** [comment]
@jcelerier Ohh, thanks for the heads-up, almost forget that.

Could you provide an example where there is a leaf and CONTENTS should not be mandatory?

**Comment by jcelerier** [comment]
Well, for instance if my namespace is : 

    /point/x ,f
    /point/y ,f

I don't think that x and y should have CONTENTS, only FULL_PATH, since they don't have children.

**Comment by lov** [comment]
@jcelerier please see my previous comment ;)

**Comment by jcelerier** [comment]
oh right, I did not see your edit, sorry.

**Comment by lov** [comment]
No worries!

**Comment by mrRay** [comment]
howdy-

i made some changes to the spec that are relevant to this discussion- please review [this commit](https://github.com/mrRay/OSCQueryProposal/commit/f7f4c505e72895f6fd12644dd67aa587a0fd9445) and let me know if there are any modifications you'd like to see to it...
