### ISSUE TITLE
[Optional extension proposal] Critical attribute

### ISSUE THREAD

**Issue by jcelerier** [Vidvox/OSCQueryProposal#34]
Hello,

For some nodes such as important triggers, etc. it may be important to offer better guarantees of success that OSC over UDP may not always be able to achieve.

To enforce this, I propose adding the following optional attribute to paths / nodes : 

    "CRITICAL": true

When a node is deemed critical, and if both endpoints support it, it means that exchanges of messages for this specific node should try to use a TCP connection if possible. For instance, it could be sent directly through the WS connection :  

    { "/my/video_player/play": null }

**Comment by mrRay** [comment]
> "When a node is deemed critical, and if both endpoints support it, it means that exchanges of messages for this specific node should try to use a TCP connection if possible. For instance, it could be sent directly through the WS connection :"

that's a neat idea, i'll add this to the spec unless there are any objections?

**Comment by mrRay** [comment]
[added here](https://github.com/mrRay/OSCQueryProposal/commit/f7f4c505e72895f6fd12644dd67aa587a0fd9445), please look it over and let me know if there are any modifications you'd like to see to it...
