### ISSUE TITLE
Attributes : allow non-array clipmodes, etc.

### ISSUE THREAD

**Issue by jcelerier** [Vidvox/OSCQueryProposal#35]
If for instance for some reason a somewhat big array (let's say 1000 elements) is sent, it seems to be a waste to send a [ "CLIP", "CLIP", "CLIP", ... ] array. 

Hence the following  proposed change : 
If an attribute has multiple elements, that all share the same value, then sending it outside the array is acceptable.

e.g. 

    "CLIPMODE": "clip"

**Comment by mrRay** [comment]
> If an attribute has multiple elements, that all share the same value, then sending it outside the array is acceptable.

i think that's a very practical insight and i'd like to add this to the spec as well!

**Comment by mrRay** [comment]
howdy-

i made some changes to the spec that are relevant to this discussion- please review [this commit](https://github.com/mrRay/OSCQueryProposal/commit/f7f4c505e72895f6fd12644dd67aa587a0fd9445) and let me know if there are any modifications you'd like to see to it...

**Comment by jcelerier** [comment]
e784c2511877ea9ef0bb68199fa7da2b5ee4f82b fixes this. thanks !
