### ISSUE TITLE
Query commands syntax

### ISSUE THREAD

**Issue by jcelerier** [Vidvox/OSCQueryProposal#36]
When actually implementing and using the protocol, I feel that it would be more natural to have the command, such as PATH_CHANGED, etc., be a json value instead of a json key. 

For instance : 

    {
        "COMMAND": "PATH_CHANGED"
        "DATA": { /* what would have been at the top level before */ }
    }

The main reason is that this allows to find the command to apply in code with a single map look-up, v.s. doing

    if(json.find("PATH_ADDED")) 
    else if(json.find("PATH_CHANGED")) 

etc...

**Comment by mrRay** [comment]
sounds good to me- tamas, how do you feel about this?

**Comment by lov** [comment]
I'm basically okay with all of the suggestions and features. I love to see them but as I mentioned here, I think what would we need is define the root principles, define the "minimal" level, etc. before pushing the proposal and the many extensions forward : https://github.com/mrRay/OSCQueryProposal/issues/25#issuecomment-281644812

**Comment by mrRay** [comment]
howdy-

i made some changes to the spec that are relevant to this discussion- please review [this commit](https://github.com/mrRay/OSCQueryProposal/commit/f7f4c505e72895f6fd12644dd67aa587a0fd9445) and let me know if there are any modifications you'd like to see to it...
