### ISSUE TITLE
_osc._udp zeroconf announcement ? / ports in zeroconf names

### ISSUE THREAD

**Issue by bltzr** [Vidvox/OSCQueryProposal#46]
after spending some time with @jcelerier working on libossia's OSCQuery compatibility, here are two things I noticed:

- some apps (notably @lov 's Mitti and @mattbeghin 's MadMapper, and @mrRay 's MIDI OSQuery Helper) not only announce OSCQuery with _oscjson._tcp (as required in the specs) but also the OSC port with _osc._udp.
Since that allowed to have libossia implementations working out of the box with Vezér (which actually requires this in order to automatically create an OSC Out port) I also added it to libossia.
Though, AFAIK, that is not specified anywhere. 
Should we add that to the specs ? At least as "best practice", since that seems to be what's people do. 
What do you guys think ?

- I also noticed that a subset of those apps (the same than above, minus @VidVox 's apps) announce their zeroconf names in the form: "zerconfName:port" (e.g. Mitti:51000) - I did a quick google search to see if that was a convention, but couldn't find anything about this. I guess that's a very minor issue (probably even a non-issue) as it's not of great importance to the end user,  but I was wondering about your opinion on this, guys (if you have any) and if we should mention this in the specs or in best practices, somewhere.

(NB: slightly related to #2 but not quite)

**Comment by bltzr** [comment]
> "a very minor issue"

I meant this is not a blocking one, but I tend to agree with you, and that's why I added this to libossia as well

**Comment by bltzr** [comment]
> The specs already contains this

Well, maybe we should still specify  more explicitly that it's recommended to announce the OSC port to zeroconf as _osc._udp , so others won't miss that info (and avoid having connection problems with Vezér ;-) )

**Comment by jcelerier** [comment]
If I remember correctly, _osc._udp had been proposed in the OSC 1.1 paper : https://pdfs.semanticscholar.org/8443/fe2707ffa283675c7beb02b03bd0763ae66c.pdf

**Comment by lov** [comment]
_osc._udp is part of the zeroconf of OSC as @jcelerier mentioned, that is not related to OSCQuery.

**Comment by bltzr** [comment]
> _osc._udp is part of the zeroconf of OSC as @jcelerier mentioned, that is not related to OSCQuery.
> 
Well, since zeroconf is completely optional (and probably not very common) in OSC, and while OSCquery is closely related to discovery matters, I thought it wouldn't do much harm (maybe just a tiny noise) adding this to the oscquery spec but I might have been wrong, and if I did I praise for your forgiveness

**Comment by bltzr** [comment]
After discussing by email with @lov I know understand why I have got confused by both those issues which, I now agree, are not part of the OSCQuery specs (so I'll close the issue with this comment):

This came up after trying to achieve automatic connections between libossia and Vezér, based on the ad-hoc convention ( ie. using both _osc._udp and the name:port format) I suppose they made between Vezér and MadMapper in order for this to happen, when the HOST_INFO part wasn't yet there.

But, now that we have HOST_INFO, this is not necessary, and as @lov pointed to them, some fallback strategies are still hinted at in the specs.

So let's close this and all make sure we implement HOST_INFO properly.
